/**
 * Agent exporter — transforms in-memory AgentDefinition objects into Claude
 * Code native subagent markdown files (`.claude/agents/*.md`).
 *
 * Each generated markdown is standalone (no NPM/MCP dependency required) and
 * carries YAML frontmatter compatible with Claude Code's `/agents` UI:
 *   - name (kebab-case, prefixed `aistack-`)
 *   - description (1-line summary)
 *   - model (claude model alias: `sonnet` | `opus` | `haiku`)
 *   - color (UI accent color for the subagent)
 *   - tools (whitelist; omit to inherit all)
 *
 * Forbidden frontmatter keys per task scope: hooks, mcpServers, permissionMode.
 *
 * This module is intentionally side-effect free at import time so it can be
 * reused by the plugin marketplace builder (AIG-629a/b) to emit identical
 * markdown into `plugin/agents/` instead of `.claude/agents/`.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { AgentDefinition } from '../types.js';
import { listAgentDefinitions } from './registry.js';

/** Claude Code model aliases supported in subagent frontmatter. */
export type ClaudeModel = 'sonnet' | 'opus' | 'haiku';

/** Per-agent export overrides keyed by `AgentDefinition.type`. */
interface AgentExportProfile {
  model: ClaudeModel;
  color: string;
  /** Whitelist of Claude Code tools the subagent may use. */
  tools: string[];
}

/**
 * Default profiles per core agent type.
 *
 * Model rationale:
 *   - `opus`: deep reasoning, adversarial critique, architectural trade-offs,
 *     multi-agent orchestration, security audits.
 *   - `sonnet`: balanced default for code/test/doc/research workloads.
 */
const DEFAULT_PROFILES: Record<string, AgentExportProfile> = {
  coder: {
    model: 'sonnet',
    color: 'blue',
    tools: ['Read', 'Edit', 'Write', 'Bash', 'Grep', 'Glob'],
  },
  researcher: {
    model: 'sonnet',
    color: 'cyan',
    tools: ['Read', 'Grep', 'Glob', 'WebSearch', 'WebFetch'],
  },
  tester: {
    model: 'sonnet',
    color: 'green',
    tools: ['Read', 'Edit', 'Write', 'Bash', 'Grep', 'Glob'],
  },
  reviewer: {
    model: 'sonnet',
    color: 'yellow',
    tools: ['Read', 'Grep', 'Glob', 'Bash'],
  },
  adversarial: {
    model: 'opus',
    color: 'red',
    tools: ['Read', 'Grep', 'Glob', 'Bash'],
  },
  architect: {
    model: 'opus',
    color: 'purple',
    tools: ['Read', 'Grep', 'Glob', 'WebSearch', 'WebFetch'],
  },
  coordinator: {
    model: 'opus',
    color: 'magenta',
    tools: ['Read', 'Grep', 'Glob', 'TodoWrite'],
  },
  analyst: {
    model: 'sonnet',
    color: 'orange',
    tools: ['Read', 'Grep', 'Glob', 'Bash'],
  },
  devops: {
    model: 'sonnet',
    color: 'gray',
    tools: ['Read', 'Edit', 'Write', 'Bash', 'Grep', 'Glob'],
  },
  documentation: {
    model: 'sonnet',
    color: 'teal',
    tools: ['Read', 'Edit', 'Write', 'Grep', 'Glob'],
  },
  'security-auditor': {
    model: 'opus',
    color: 'red',
    tools: ['Read', 'Grep', 'Glob', 'Bash', 'WebSearch'],
  },
};

/** Conservative fallback for custom/unknown agents. */
const FALLBACK_PROFILE: AgentExportProfile = {
  model: 'sonnet',
  color: 'blue',
  tools: ['Read', 'Grep', 'Glob'],
};

/** Prefix applied to every exported subagent name to avoid collisions. */
export const AGENT_NAME_PREFIX = 'aistack-';

export interface ExportAgentOptions {
  /**
   * Override the default profile for a given agent type. Useful for tests and
   * for the plugin marketplace builder that may want different tool sets.
   */
  profiles?: Record<string, Partial<AgentExportProfile>>;
}

/**
 * Convert one AgentDefinition into a Claude Code subagent markdown document.
 * Pure function — no filesystem side effects.
 */
export function exportAgentToMarkdown(
  agent: AgentDefinition,
  options: ExportAgentOptions = {},
): string {
  const base = DEFAULT_PROFILES[agent.type] ?? FALLBACK_PROFILE;
  const override = options.profiles?.[agent.type] ?? {};
  const profile: AgentExportProfile = {
    model: override.model ?? base.model,
    color: override.color ?? base.color,
    tools: override.tools ?? base.tools,
  };

  const name = `${AGENT_NAME_PREFIX}${agent.type}`;
  const description = singleLine(agent.description);

  const frontmatter = [
    '---',
    `name: ${name}`,
    `description: ${yamlString(description)}`,
    `model: ${profile.model}`,
    `color: ${profile.color}`,
    `tools: ${formatToolList(profile.tools)}`,
    '---',
  ].join('\n');

  const header = `# ${agent.name}`;
  const intro =
    `> Exported from the aistack agent registry (type: \`${agent.type}\`).\n` +
    `> Generated by \`aistack export-agents\` — see https://github.com/blackms/aistack.\n` +
    `> This file is standalone: it does not require the aistack NPM package to be installed.`;

  const capabilities = agent.capabilities.length > 0
    ? `## Capabilities\n\n${agent.capabilities.map((c) => `- ${c}`).join('\n')}`
    : '';

  const body = agent.systemPrompt.trimEnd();

  const parts = [frontmatter, '', header, '', intro, ''];
  if (capabilities) {
    parts.push(capabilities, '');
  }
  parts.push(body, '');

  return parts.join('\n');
}

/**
 * Write all registered agent definitions into `outputDir` as
 * `aistack-<type>.md`. Creates the directory if missing.
 *
 * Returns the absolute paths of the files written, in deterministic order.
 */
export async function exportAllAgents(
  outputDir: string,
  options: ExportAgentOptions = {},
): Promise<string[]> {
  await mkdir(outputDir, { recursive: true });

  const definitions = listAgentDefinitions();
  // Sort for deterministic output (test stability + clean diffs)
  const ordered = [...definitions].sort((a, b) => a.type.localeCompare(b.type));

  const written: string[] = [];
  for (const def of ordered) {
    const filename = `${AGENT_NAME_PREFIX}${def.type}.md`;
    const filepath = join(outputDir, filename);
    const content = exportAgentToMarkdown(def, options);
    await writeFile(filepath, content, 'utf8');
    written.push(filepath);
  }

  return written;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function singleLine(input: string): string {
  return input.replace(/\s+/g, ' ').trim();
}

/**
 * YAML-safe string emitter. Always quotes to avoid surprises with special
 * characters (`:`, `#`, leading `-`, etc.) inside descriptions.
 */
function yamlString(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

/** Render a tool list as a YAML flow sequence: `[Read, Edit, Bash]`. */
function formatToolList(tools: string[]): string {
  return `[${tools.join(', ')}]`;
}
